### ISSUE TITLE
Fonts don't render on Linux

### ISSUE THREAD

**Issue by konklone** [usagov/usa.gov#1]
The site specifies `Tahoma, Verdana, Arial, sans-serif`, but on Linux I only get `sans-serif`, which isn't very flattering:

![screenshot from 2015-05-06 12 17 14](https://cloud.githubusercontent.com/assets/4592/7497762/9cef4a82-f3ea-11e4-9ce9-bbce252d078e.png)

Have you considered using some fonts from [Google Fonts](https://www.google.com/fonts)? You can also [inline these fonts](https://github.com/18F/18f.gsa.gov/pull/672) to avoid having to ping `fonts.googleapis.com`.

**Comment by smileytech** [comment]
Thanks for the feedback!  We did consider using web fonts, but decided against it because the vast majority of our users use  browsers that support Tahoma or Verdana, and we didn’t think it was worth the extra download requirement to  use a web font.

**Comment by konklone** [comment]
@smileytech You can also self-host Google Fonts, which removes the third-party ping. If your host supports SPDY or HTTP/2 (it looks like usa.gov doesn't currently) then downloading the additional resources from your own host would be negligible latency.
