### ISSUE TITLE
Re USE CASE 2, Item 2

### ISSUE THREAD

**Issue by samhsa-arlene** [usagov/usa.gov#10]
Questionnaire item refers to clicking on 'state, local and tribal gov't' - on the site it's actually called ' state and tribal govts' (the word 'local' is not there).

**Comment by samhsa-arlene** [comment]
ALSO related to this issue, the site where I then land is again called 'state and tribal govs' and the URL is https://beta.usa.gov/states-and-territories - NOT '/state-LOCAL-tribal-govts.'

**Comment by LCY-M** [comment]
Corrections in the test script:

USE CASE 2, Item 2 - From beta.USA.gov, tab on 'Menu', and tap on '**Government** Agencies and Elected Officials'

USE CASE 2, Item 3 Tap on 'State and Tribal Governments' under 'Government Agencies and Elected Officials' page.

Thank you for pointing this out. 

:blush:

**Comment by michellechronister** [comment]
We removed local from the titles after the test questions were written because we decided not to publish that content. Sorry about that. Thanks for testing!
