### ISSUE TITLE
re USE CASE 3, #1

### ISSUE THREAD

**Issue by samhsa-arlene** [usagov/usa.gov#11]
When I searched for 'per diem rates,' had a long list of results, though one was 'recommended' by the site.

**Comment by LCY-M** [comment]
When you search for 'per diem rates',  the site will display a long list of results.  Tap on the first result and explore the page.  Yes, the first displayed one on the result list is recommended by USA.gov Beta. 

:smile:

**Comment by michellechronister** [comment]
Yes, the first result is the one that's recommended by USA.gov. Thanks for testing!
