### ISSUE TITLE
RE Use Case 3, Item 3

### ISSUE THREAD

**Issue by samhsa-arlene** [usagov/usa.gov#12]
Hi, this could just be me but I ended up looking all over the site for 'what's on this page' til it occurred to me to return to where I'd just been at which point I finally registered that it was the blued box. Maybe make the headline a tiny bit bigger?

**Comment by samhsa-arlene** [comment]
An aside, but when I clicked on the first item under 'what's on this page,' to me it was confusing to see that section but then the rest of the whole page underneath, with a 'back to top' note with red arrow above the following section.

**Comment by LCY-M** [comment]
I will include your suggestions in the test report.

**Comment by michellechronister** [comment]
Thanks for your feedback about the "what's on this page" box. It's meant to highlight the items on the page so people on mobile can easily see the topics without scrolling. When you click one, you jump down the page to that section (it's an anchor link). The back to top link allows you to quickly go back to the what's on this page box. We will consider your suggestions for future iterations.
