### ISSUE TITLE
Case 3, Item 4

### ISSUE THREAD

**Issue by samhsa-arlene** [usagov/usa.gov#13]
On my tablet, the word 'What' in survey headline comes out white font on yellow background @@.

But I was able to complete the survey, to provide more than one response when asked to, etc.

**Comment by LCY-M** [comment]
I will include this finding in the test report.

**Comment by michellechronister** [comment]
@samhsa-arlene Can you provide a screen shot of this?

**Comment by samhsa-arlene** [comment]
Michelle,

Heck, I can’t find the email where you gave me the survey monkey thingie so I could identify what the actual item was – what was I asked to do that led to my comment etc. Could you re-send the link and I’ll zap a screenshot?

A

**Comment by michellechronister** [comment]
Sure. Here's the task: Click on the menu and search for per diem rates. Tap on the first result and explore the page. Please tap on a link in the What’s on This Page box. You should drop down the page to that content. At the bottom of the page is a survey, please take it and enter TEST in the open text field.

We are no longer in beta, so you can't perform this task as written. Please visit https://www.usa.gov/benefits-for-federal-employees (which is the same page as the task). I'm specifically interested in the white font on yellow background. Thank you!

**Comment by samhsa-arlene** [comment]
Michelle, finally getting back to you:

Here’s what happened mid-way through, though this time the box didn’t interfere with proceeding, I was able to go to the link. There was kind of an annoying pop-up though, asking if I wanted mobile or full site. I didn’t realize it was going to keep coming up in the same session so kept seeing it til I told it to stop showing the message or whatever :”}.

Hope this helps and thanks for letting me close the circle! Arlene@SAMHSA

[cid:__storage_sdcard0_Pictures_Screenshots_Screenshot_2015-07-08-14-09-04_png@sec.galaxytab]

**Comment by michellechronister** [comment]
Thanks for following up Arlene! Unfortunately, the image didn't come through on GitHub or email. Could you email it to me directly at michelle.chronister@gsa.gov?
