### ISSUE TITLE
CASE 4, Item 1

### ISSUE THREAD

**Issue by samhsa-arlene** [usagov/usa.gov#14]
URL I landed at for 'government agencies and elected officials' (DIFFERENT ON SITE Vs. in your questionnaire) is actually https://beta.usa.gov/agencies, NOT ...'federal-govt'.

**Comment by LCY-M** [comment]
Correction:

CASE 4, Item 1 Expected Result -- The user should be navigated to the "Federal Agencies and Branches of Government" page http://beta.usa.gov/agencyies 

:blush:

**Comment by samhsa-arlene** [comment]
Hi,

just noticed that in the link here, 'agencies' is misspelled - but that would not reflect what was actually on the aite, right?

Sent from Samsung tablet

-------- Original message --------

**Comment by LCY-M** [comment]
Yes, it should be https://beta.usa.gov/agencies.   Thanks.
