### ISSUE TITLE
CASE 4, Item 3

### ISSUE THREAD

**Issue by samhsa-arlene** [usagov/usa.gov#15]
Took quite a while for the site to come up when I clicked on the A-Z Index - when I did so repeatedly, there was an orange box surrounding what I was trying to click, which seemed to 'touch' the column alongside and almost seemed to be interfering with matters.

**Comment by samhsa-arlene** [comment]
Just noticed, URL for page I was sent to ends with 's' not 'a' after last slash.

**Comment by LCY-M** [comment]
Thanks for the finding.  I will include it in the test report.

**Comment by michellechronister** [comment]
We know there's a long load time for the A-Z index and we're actively working to fix it. 

The orange box that surrounds the link title is there for accessibility reasons. It's to ensure that keyboard users know where the focus is on the page. Usually, you only see it for a second unless you're using the keyboard. We'll look into why it was interfering on mobile.

**Comment by samhsa-arlene** [comment]
Hi Michelle, yeah, that box was overlapping onto the next column and persisting quite a while. I finally got it to work just by jabbing, nudging etc. ;’]   Mind you, my tablet’s getting a little long in the tooth… ;’]

Arlene@SAMHSA

**Comment by michellechronister** [comment]
Thanks @samhsa-arlene!
