### ISSUE TITLE
re CASE 4, Item 4

### ISSUE THREAD

**Issue by samhsa-arlene** [usagov/usa.gov#16]
WAS able to find my agency, SAMHSA, by full name, not by the well-known acronym, using both methods. (People don't always remember what the associated words are.)

**Comment by samhsa-arlene** [comment]
Noticed on the SAMHSA contact page that the email was misspelled, showed as '@saNhsa.hhs.gov' - 'N' instead of 'm' .

**Comment by LCY-M** [comment]
:+1: 

Thanks for finding this.  I will include it in the test report.

**Comment by michellechronister** [comment]
Thanks for the suggestion and for finding the typo. We'll fix it.
