### ISSUE TITLE
Gobierno.Gov Test Case 3

### ISSUE THREAD

**Issue by laurakahn2** [usagov/usa.gov#17]
The first search result doesn't go to the  "VISAS DE TURISMO Y NEGOCIOS" page http://spanish.mexico.usembassy.gov/es/visas.html. It goes to the beta.gobierno.gov/inmigrantes-noresidentes page

**Comment by LCY-M** [comment]
Thanks for the finding.  I will include it in the test report.

**Comment by michellechronister** [comment]
Thanks @laurakahn2! We have modified the scope of our search so this is no longer an issue. Sorry if it hindered your ability to test.
