### ISSUE TITLE
Misleading information under Jobs and Unemployment

### ISSUE THREAD

**Issue by tlkoebel** [usagov/usa.gov#6]
I want to flag that "public sector" means government employment. When I saw the descriptive text below I assumed I was going to a page about jobs within government (state, local and federal). I believe the simple fix here is to change "public" to "private."

"Looking for a New Job
Find out about looking for work in the public sector and federal government."

This text appears on at least two pages that I could find:
http://beta.usa.gov/jobs-and-unemployment
http://beta.usa.gov/job-search

-Tiffany 
DOL Office of Public Affairs, digital media team

**Comment by smileytech** [comment]
Thanks!  We've updated those two pages.

**Comment by tlkoebel** [comment]
Great, thanks for the response!
