### ISSUE TITLE
Serve higher-resolution icons to HiDPI displays

### ISSUE THREAD

**Issue by citelao** [usagov/usa.gov#7]
Images are currently served assuming 72dpi, so icons on HiDPI displays do not look sharp (compare icons with button text):

![Screenshot showing jaggies on images; compare to text](https://cloud.githubusercontent.com/assets/432939/7843534/2e66c114-0478-11e5-8098-7413dcb1f507.png)

**Comment by smileytech** [comment]
Thanks for the feedback!  We don’t load High-DPI versions of images mainly to keep the page size as small as possible.  However, we’re looking into switching our icons to SVG from PNG images which should help ensure they look great on all displays.

**Comment by citelao** [comment]
:+1: I figured that was a consideration.
