### ISSUE TITLE
Use Gov.uk as a model

### ISSUE THREAD

**Issue by nsinai** [usagov/usa.gov#8]
I'd suggest using Gov.uk as a model -- both in how it was developed, and also in design

How it was developed:
=> https://gds.blog.gov.uk/colophon-alpha/
=> https://gds.blog.gov.uk/2011/08/11/gov-uk-from-alpha-to-beta/
=> https://gds.blog.gov.uk/2011/07/29/alpha-gov-uk-wrap-up/
=> https://gds.blog.gov.uk/2011/05/23/what-was-the-evidence-users-information-needs-and-analytics/

The current Digital Service Standard in the UK:
=> https://gds.blog.gov.uk/2015/05/29/shorter-but-just-as-sweet-the-revised-and-updated-digital-service-standard/

Current design of gov.uk
=> https://www.gov.uk/

**Comment by smileytech** [comment]
Thanks for the feedback!  We definitely looked at Gov.uk when designing the new site.
